---
- name: setup webservers
  gather_facts: yes
  #remote_user: root
  remote_user: ansible
  become: yes
  become_method: sudo
  hosts: web
  #hosts: all
  vars_files:
    -  defaults/main.yml
    #-  defaults/secrets.yml

  roles:
    - web

