---

- name: setup test postgres
  gather_facts: yes
  #remote_user: root
  remote_user: ansible
  become: yes
  become_method: sudo
  hosts: test-postgres
  vars_files:
    -  defaults/main.yml
    #-  defaults/secrets.yml

  roles:
    - postgres

- name: setup test netbox
  gather_facts: yes
  #remote_user: root
  remote_user: ansible
  become: yes
  become_method: sudo
  hosts: test-netbox
  vars_files:
    -  defaults/main.yml
    #-  defaults/secrets.yml

  roles:
    - netbox


- name: setup test haproxy
  gather_facts: yes
  #remote_user: root
  remote_user: ansible
  become: yes
  become_method: sudo
  hosts: test-haproxy
  vars_files:
    -  defaults/main.yml
    #-  defaults/secrets.yml

  roles:
     - haproxy