---
- name: setup single node netbox
  gather_facts: yes
  #remote_user: root
  remote_user: ansible
  become: yes
  become_method: sudo
  hosts: prod-netbox
  vars_files:
    -  defaults/main.yml
    #-  defaults/secrets.yml

  roles:
    - postgres
    - netbox
    - haproyx