---
- name: setup test netbox
  gather_facts: yes
  #remote_user: root
  remote_user: ansible
  become: yes
  become_method: sudo
  hosts: prod-netbox
  vars_files:
    -  defaults/main.yml
    #-  defaults/secrets.yml

  roles:
    - netbox

- name: setup test postgres
  gather_facts: yes
  #remote_user: root
  remote_user: ansible
  become: yes
  become_method: sudo
  hosts: prod-postgres
  vars_files:
    -  defaults/main.yml
    #-  defaults/secrets.yml

  roles:
    - postgres


- name: setup test haproxy
  gather_facts: yes
  #remote_user: root
  remote_user: ansible
  become: yes
  become_method: sudo
  hosts: prod-happroxy
  vars_files:
    -  defaults/main.yml
    #-  defaults/secrets.yml

  roles:
    - haproyx